import headline from "../evidence/headline.json";

/**
 * The argument, above the fold, from a committed file with zero backend calls.
 *
 * Everything else on this page needs a live backend and a run. Render cold-starts, the deployed
 * default provider cannot run a local model, and backends go down on judging day. If any of that
 * happens, this section still renders the entire finding.
 *
 * headline.json is generated by backend/scripts/export_headline_evidence.py out of the same evidence
 * files docs/RESULTS.md quotes, so the front page cannot drift from the results doc.
 */

const pct = (n: number) => `${n.toFixed(1)}%`;

function Delta({ value }: { value: number }) {
  return <span className={`hero-delta${value <= -20 ? " hero-delta-severe" : ""}`}>{value > 0 ? "+" : ""}{value.toFixed(1)}</span>;
}

export function HeroFindings() {
  const { reading, three_source, negative, footer } = headline;

  return (
    <section className="hero">
      <div className="hero-lede">
        <h2>Every category I built for the model fell to a rule I wrote afterwards.</h2>
        <p>
          Settlement records come from deterministic processes, so their ground truth is arithmetically derivable and a
          rule always wins. So the resolver runs first and the model only sees what it could not finish. These three
          findings are what that measured.
        </p>
      </div>

      <div className="hero-cards">
        {/* ---- 1. where AI belongs -------------------------------------------------------- */}
        <article className="hero-card">
          <h3>Where AI belongs</h3>
          <p className="hero-card-sub">Reading bank remittance advice. {reading.judgements_per_cell} judgements per cell.</p>
          <table className="hero-table">
            <thead>
              <tr>
                <th />
                <th>phrasing the author saw</th>
                <th>phrasing he didn't</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {reading.rows.map((r) => (
                <tr key={r.label} className={r.is_rule ? "is-rule" : "is-model"}>
                  <td className="hero-row-label">{r.label}</td>
                  <td className="num">{pct(r.seen.pct)}</td>
                  <td className="num strong">{pct(r.held_out.pct)}</td>
                  <td className="num"><Delta value={r.delta} /></td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="hero-punch">
            On unfamiliar phrasing the rule asserts charges the text explicitly denies,{" "}
            <span className="hero-danger">{pct(reading.danger.rule_pct)}</span> of the time.
          </p>
          <p className="hero-foot">
            {reading.danger.rule_count} of {reading.judgements_per_cell}. Both models sit at{" "}
            {pct(reading.danger.model_pct_low)}–{pct(reading.danger.model_pct_high)}, and their errors run the other
            way: they miss the mention, so the case escalates.
          </p>
        </article>

        {/* ---- 2. where it pays ----------------------------------------------------------- */}
        <article className="hero-card">
          <h3>Where it pays</h3>
          <p className="hero-card-sub">
            Three-source matching. Same matcher, same filters, same weights. Only the cycle reader changes.
          </p>
          <table className="hero-table">
            <thead>
              <tr>
                <th />
                <th>seen</th>
                <th>held-out</th>
              </tr>
            </thead>
            <tbody>
              {three_source.rows.map((r) => (
                <tr key={r.label} className={r.is_rule ? "is-rule" : r.label.startsWith("qwen") ? "is-model" : ""}>
                  <td className="hero-row-label">{r.label}</td>
                  <td className="num">{pct(r.seen.pct)}</td>
                  <td className="num strong">{pct(r.held_out.pct)}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="hero-punch">
            The regex buys nothing on held-out phrasing. {pct(three_source.rows[1].held_out.pct)}, identical to not
            parsing at all.
          </p>
          <p className="hero-foot">
            The model wins {three_source.mcnemar.wins} paired cases and loses {three_source.mcnemar.losses}, exact
            McNemar <span className="mono">p = {three_source.mcnemar.p.toFixed(3)}</span>. Conceding 2 cases takes that
            to p = {three_source.mcnemar.p_conceding_2.toFixed(2)}, so it is significant and not robust.
          </p>
        </article>

        {/* ---- 3. where it doesn't -------------------------------------------------------- */}
        <article className="hero-card">
          <h3>Where it doesn't</h3>
          <p className="hero-card-sub">Compound residual, held-out phrasing. My own negative result.</p>
          <table className="hero-table">
            <tbody>
              <tr className="is-floor">
                <td className="hero-row-label">chance, computed as 1/k</td>
                <td className="num">{pct(negative.chance_pct)}</td>
              </tr>
              <tr>
                <td className="hero-row-label">parsimony, ignores the text</td>
                <td className="num strong">{pct(negative.parsimony.pct)}</td>
              </tr>
              <tr className="is-model">
                <td className="hero-row-label">qwen2.5:14b-instruct</td>
                <td className="num strong">{pct(negative.model.pct)}</td>
              </tr>
            </tbody>
          </table>
          <p className="hero-punch">
            A free heuristic that ignores the advice entirely is at least as good as any reader.
          </p>
          <p className="hero-foot">
            {negative.mcnemar.wins} discordant one way, {negative.mcnemar.losses} the other, exact McNemar{" "}
            <span className="mono">p = {negative.mcnemar.p.toFixed(2)}</span>. Not distinguishable at n=
            {negative.parsimony.total}. Where free text competes with a structural prior, reading did not help.
          </p>
        </article>
      </div>

      <p className="hero-close">
        <span className="num">{pct(footer.demo_closed_pct)}</span> of a batch closes deterministically at demo density,{" "}
        <span className="num">{pct(footer.realistic_closed_pct)}</span> at realistic density. The model runs{" "}
        <span className="num">{footer.slower_factor.toLocaleString()}×</span> slower and only ever sees what the resolver
        couldn't finish.
      </p>
    </section>
  );
}
