"""Three sources that disagree — the actual production reconciliation problem.

Everything else in this project reconciles Razorpay-side data against itself: one settlement record,
one ledger entry, one causal chain, all generated by the same process with referential integrity
guaranteed by construction. That makes the matching step trivial and pushes all the difficulty into
the *arithmetic*, which is why the arithmetic is where every hard case in this repo has lived.

Real reconciliation is not shaped like that. It is three systems that never agreed in the first place:

    SETTLEMENT REPORT   what the payment gateway says it paid out
    BANK STATEMENT      what actually landed in the merchant's account, described by a bank
    ERP LEDGER          what the merchant's own books expected, entered by a person or an import job

Nothing joins them cleanly. Banks truncate the UTR, or prefix it, or drop leading zeros. Bank
statements carry a free-text description with the merchant's name abbreviated however that particular
bank abbreviates it. Value dates slip by a day or two across a weekend. The ERP records a rounded
figure, or one net of a fee the gateway reported gross, or batches several payouts into one line.

That is where deterministic matching genuinely breaks at the margin, and it breaks in exactly the
shape this project's residual architecture is built for: an exact join resolves most rows outright,
and the remainder is not "unsolved" but *under-determined* — several bank rows could each legitimately
be this settlement, and no amount of better joining logic decides between them, because the
information that decides is in the description text and the surrounding context rather than in a key.

Corruptions applied here are the ones that actually occur, each independently toggled so the evidence
can attribute a failure to a specific cause rather than to "messy data" in general:

    utr_truncated       bank keeps only the last 6-8 characters
    utr_prefixed        bank prepends its own scheme code (NEFT/, IMPS-, UTR:)
    date_shift          value date lands 1-3 days late, weekends included
    name_abbreviated    merchant name rendered in that bank's own house style
    amount_rounded      ERP records to the nearest rupee, losing the paise
    batched             several settlements arrive as one bank credit
"""

import random
import string
from datetime import datetime, timedelta

from pydantic import BaseModel

# Bank house styles for rendering a merchant name -- each bank abbreviates differently, and none of
# them agrees with how the merchant's own ERP spells it.
_NAME_STYLES = (
    lambda n: n.upper().replace("_", " "),
    lambda n: n.upper().replace("_", "")[:12],
    lambda n: "".join(p[0] for p in n.split("_")).upper() + n.split("_")[-1][:4].upper(),
    lambda n: n.replace("_", "-").title(),
    lambda n: n.upper().replace("MERCHANT", "MRCHNT").replace("_", ""),
)

_SCHEME_PREFIXES = ("NEFT/", "IMPS-", "UTR:", "RTGS/", "")

# The first template is Razorpay's OWN documented settlement narration, from their settlements
# documentation: "NEFT CR: [bank name] [UTR] RAZORPAY SETTLEMENT". It is the only one of these that
# is not my invention. The other five are plausible bank house styles I wrote, and LIMITATIONS says
# what that costs.
_BANK_DESC_TEMPLATES = (
    "NEFT CR: {bank} {utr} RAZORPAY SETTLEMENT",
    "{scheme}{utr} {name} SETTLEMENT",
    "{name}/{scheme}{utr}",
    "CR-{scheme}{utr}-{name}",
    "{scheme}{utr}//{name}//PG PAYOUT",
    "NET STL {name} REF {utr}",
)

# Slot letters a gateway's daily cycles are labelled with. Two payouts in the same slot on the same
# day, to the same merchant, for the same amount, are the one case nothing can separate.
_CYCLE_SLOTS = "ABCD"

# Real Indian bank identifiers, as they appear inside a narration.
_BANKS = ("HDFC", "ICIC", "SBIN", "UTIB", "KKBK", "YESB")


class SettlementRow(BaseModel):
    """What the gateway says it paid out. The reference view."""

    settlement_id: str
    utr: str
    merchant_id: str
    amount: int  # paise
    value_date: datetime
    # The settlement cycle this payout belongs to (e.g. "C2026-03-14-A"). Gateways really do run
    # several cycles a day, and this is the one field that still distinguishes two otherwise-identical
    # payouts to the same merchant. Banks carry it only sometimes, only in the free-text description,
    # and never in a fixed position -- which is exactly what makes it a reading problem rather than a
    # join problem. See `identical_twin_rate` in `generate`.
    cycle_ref: str = ""


class BankRow(BaseModel):
    """What the bank says landed, described the way a bank describes things."""

    bank_row_id: str
    description: str  # free text: the only place the UTR and merchant name appear at all
    credit_amount: int
    value_date: datetime


class LedgerRow(BaseModel):
    """What the merchant's own books expected."""

    ledger_row_id: str
    merchant_id: str
    expected_amount: int
    recorded_date: datetime
    reference_note: str


class ThreeSourceBatch(BaseModel):
    settlements: list[SettlementRow]
    bank_rows: list[BankRow]
    ledger_rows: list[LedgerRow]
    # settlement_id -> the bank_row_id that genuinely corresponds to it. Scoring only; never read by
    # any matcher, exactly like every other ground-truth structure in this project.
    truth: dict[str, str]
    # settlement_id -> which corruptions were applied, so a failure can be attributed to a cause
    corruptions: dict[str, list[str]]


class ThreeSourceGenerator:
    def __init__(self, seed: int = 42) -> None:
        self.rng = random.Random(seed)
        # Which bank appears inside a narration is cosmetic -- it is never matched on. It gets its
        # own stream so that adding it did not shift every downstream draw and silently re-roll the
        # whole batch, which would have made "before the format was added" and "after" two different
        # random draws rather than a controlled comparison.
        self._cosmetic_rng = random.Random(seed + 7919)
        self.base_date = datetime(2026, 3, 1)

    def _utr(self) -> str:
        return "".join(self.rng.choices(string.digits, k=12))

    # How a bank renders the settlement cycle when it carries it at all. Deliberately inconsistent in
    # separator, casing, position and abbreviation -- a fixed-position parse works on one of these and
    # fails on the rest, which is the whole point.
    _CYCLE_STYLES = (
        lambda d, c: f"{d} CYCLE {c}",
        lambda d, c: f"{d}/{c}",
        lambda d, c: f"{c} {d}",
        lambda d, c: f"{d} (batch {c.lower()})",
        lambda d, c: f"{d} STL-CYC-{c.replace('-', '')}",
        lambda d, c: f"{d} ref.cyc {c.split('-')[-1]} of {'-'.join(c.split('-')[:-1]).lstrip('C')}",
    )

    # House styles a cycle parser written against the bank above has never seen: dotted and
    # abbreviated dates, "run"/"window"/"slot" instead of "cycle", the slot letter separated from its
    # date entirely. All of them state the same fact and all remain readable; none of them matches the
    # regexes in app/resolver/entity_resolution.py. Same held-out discipline as the remittance-advice
    # phrase banks, applied to the join problem instead of the arithmetic one.
    _CYCLE_STYLES_HELDOUT = (
        lambda d, c: f"{d} SETTLEMENT RUN {c.rsplit('-', 1)[1]} DTD {c.lstrip('C').rsplit('-', 1)[0].replace('-', '.')}",
        lambda d, c: f"{d} | window {c.rsplit('-', 1)[1]} on {c.lstrip('C').rsplit('-', 1)[0]}",
        lambda d, c: f"{d} SR/{c.rsplit('-', 1)[1]}/{c.lstrip('C').rsplit('-', 1)[0].replace('-', '')}",
        lambda d, c: f"{d} - processed in slot {c.rsplit('-', 1)[1].lower()} of {c.lstrip('C').rsplit('-', 1)[0]}",
        lambda d, c: f"{d} [run {c.rsplit('-', 1)[1]}, {c.lstrip('C').rsplit('-', 1)[0].replace('-', '/')}]",
    )

    def _attach_cycle(self, description: str, cycle_ref: str, held_out: bool = False) -> str:
        styles = self._CYCLE_STYLES_HELDOUT if held_out else self._CYCLE_STYLES
        return self.rng.choice(styles)(description, cycle_ref)

    def _corrupt_utr(self, utr: str, applied: list[str]) -> str:
        out = utr
        if self.rng.random() < 0.45:
            keep = self.rng.choice([6, 7, 8])
            out = out[-keep:]
            applied.append("utr_truncated")
        if self.rng.random() < 0.5:
            scheme = self.rng.choice(_SCHEME_PREFIXES)
            if scheme:
                out = scheme + out
                applied.append("utr_prefixed")
        return out

    def generate(self, n: int = 120, collision_rate: float = 0.25, identical_twin_rate: float = 0.25, held_out_cycle_phrasing: bool = False) -> ThreeSourceBatch:
        """`collision_rate` gives a settlement a NEAR-twin: same merchant, amount within a rupee,
        value date a day or two apart. A well-written matcher separates those, and the first version
        of this generator stopped there — a rule scored 119/120, which said more about the generator
        than about entity resolution.

        `identical_twin_rate` is the case that actually occurs and actually breaks a join: **two
        payouts to the same merchant, for exactly the same amount, on exactly the same day**. Any
        subscription or marketplace business produces these constantly. Amount and date stop
        discriminating entirely, the UTRs share a truncated tail, and the only thing left that
        separates them is the settlement cycle reference — which the bank carries in free text, in
        whatever position and format that bank happens to use, and often not at all.

        That is deliberately the same shape as this project's remittance-advice finding, arrived at
        from a different direction: the structured fields run out, and what remains is a reading
        problem."""
        settlements: list[SettlementRow] = []
        bank_rows: list[BankRow] = []
        ledger_rows: list[LedgerRow] = []
        truth: dict[str, str] = {}
        corruptions: dict[str, list[str]] = {}

        merchants = [f"merchant_{i:03d}" for i in range(1, 9)]

        for i in range(n):
            merchant = self.rng.choice(merchants)
            amount = self.rng.choice([50_000, 125_000, 249_900, 375_000, 512_450, 1_000_000, 2_499_900])
            value_date = self.base_date + timedelta(days=self.rng.randint(0, 25))
            utr = self._utr()
            settlement = SettlementRow(
                settlement_id=f"stl_{i:04d}_{self.rng.randrange(16**6):06x}",
                utr=utr,
                merchant_id=merchant,
                amount=amount,
                value_date=value_date,
                cycle_ref=f"C{value_date.date().isoformat()}-{self.rng.choice('ABCD')}",
            )
            settlements.append(settlement)
            applied: list[str] = []

            # --- the bank's view of the same payout ---------------------------------------------
            bank_utr = self._corrupt_utr(utr, applied)
            style = self.rng.choice(_NAME_STYLES)
            bank_name = style(merchant)
            if bank_name != merchant.upper().replace("_", " "):
                applied.append("name_abbreviated")
            shift = 0
            if self.rng.random() < 0.4:
                shift = self.rng.randint(1, 3)
                applied.append("date_shift")
            description = self.rng.choice(_BANK_DESC_TEMPLATES).format(
                scheme="", utr=bank_utr, name=bank_name, bank=self._cosmetic_rng.choice(_BANKS)
            )
            # The cycle reference, when the bank carries it at all: appended, prefixed, or embedded,
            # in one of several house formats. Around a third of banks drop it entirely, which is why
            # it can never be relied on as a key and has to be read for when it is there.
            if self.rng.random() < 0.65:
                description = self._attach_cycle(description, settlement.cycle_ref, held_out=held_out_cycle_phrasing)
                applied.append("cycle_ref_present")
            bank_row = BankRow(
                bank_row_id=f"bnk_{i:04d}_{self.rng.randrange(16**6):06x}",
                description=description,
                credit_amount=amount,
                value_date=value_date + timedelta(days=shift),
            )
            bank_rows.append(bank_row)
            truth[settlement.settlement_id] = bank_row.bank_row_id

            # --- the merchant's own books ---------------------------------------------------------
            expected = amount
            if self.rng.random() < 0.5:
                expected = round(amount, -2)  # ERP keeps whole rupees
                applied.append("amount_rounded")
            ledger_rows.append(
                LedgerRow(
                    ledger_row_id=f"lgr_{i:04d}_{self.rng.randrange(16**6):06x}",
                    merchant_id=merchant,
                    expected_amount=expected,
                    recorded_date=value_date - timedelta(days=self.rng.randint(0, 2)),
                    reference_note=f"PG settlement {merchant} {value_date.date().isoformat()}",
                )
            )

            corruptions[settlement.settlement_id] = applied

        # --- near-twins: the rows that make a truncated UTR stop being a key ----------------------
        n_collisions = int(len(settlements) * collision_rate)
        for settlement in self.rng.sample(settlements, k=min(n_collisions, len(settlements))):
            twin_utr = self._utr()
            # share the truncated tail with the original, which is exactly what makes a
            # last-6-digits join ambiguous rather than merely lossy
            twin_utr = twin_utr[:6] + settlement.utr[-6:]
            style = self.rng.choice(_NAME_STYLES)
            twin_amount = settlement.amount + self.rng.choice([-100, -50, 0, 50, 100])
            twin_date = settlement.value_date + timedelta(days=self.rng.choice([-2, -1, 1, 2]))
            bank_rows.append(
                BankRow(
                    bank_row_id=f"bnk_twin_{self.rng.randrange(16**8):08x}",
                    description=self.rng.choice(_BANK_DESC_TEMPLATES).format(
                        scheme="",
                        utr=twin_utr[-self.rng.choice([6, 7, 8]) :],
                        name=style(settlement.merchant_id),
                        bank=self._cosmetic_rng.choice(_BANKS),
                    ),
                    credit_amount=twin_amount,
                    value_date=twin_date,
                )
            )
            corruptions[settlement.settlement_id].append("near_twin_present")

        # --- identical twins: same merchant, same amount, same day ---------------------------------
        # A second REAL settlement, not a decoy: it gets its own settlement row, its own bank row, and
        # its own entry in `truth`, so getting the pair the wrong way round is scored as two errors
        # rather than one. Its UTR shares a truncated tail with its twin's, so once the bank drops
        # digits the two are indistinguishable on every structured field. Only the cycle reference
        # separates them, and only when the bank carried it.
        n_identical = int(len(settlements) * identical_twin_rate)
        for original in self.rng.sample(settlements, k=min(n_identical, len(settlements))):
            twin_utr = "".join(self.rng.choices(string.digits, k=6)) + original.utr[-6:]
            # The twin must differ on cycle from EVERY settlement it is otherwise identical to, not
            # merely from the one it was cloned from. Guarding only against the original let two
            # twins of the same group draw the same slot letter, producing settlements that agree on
            # merchant, amount, date AND cycle -- indistinguishable by any method, so no reader could
            # ever be scored fairly on them. The generalisation suite caught it; it was 30 rows across
            # ten seeds and 2% of all errors, small enough to have gone unnoticed and still wrong.
            day = original.value_date.date().isoformat()
            taken = {
                s.cycle_ref for s in settlements
                if (s.merchant_id, s.amount, s.value_date) == (original.merchant_id, original.amount, original.value_date)
            }
            free = [c for c in _CYCLE_SLOTS if f"C{day}-{c}" not in taken]
            if not free:
                # More same-day payouts to one merchant for one amount than there are cycles to put
                # them in. Skipping is right: inventing a slot the gateway does not run would make
                # the case separable by something that does not exist.
                continue
            twin_cycle = f"C{day}-{self.rng.choice(free)}"
            twin = SettlementRow(
                settlement_id=f"stl_tw_{self.rng.randrange(16**8):08x}",
                utr=twin_utr,
                merchant_id=original.merchant_id,
                amount=original.amount,
                value_date=original.value_date,
                cycle_ref=twin_cycle,
            )
            settlements.append(twin)

            applied = ["identical_twin"]
            bank_utr = self._corrupt_utr(twin_utr, applied)
            desc = self.rng.choice(_BANK_DESC_TEMPLATES).format(
                scheme="",
                utr=bank_utr,
                name=self.rng.choice(_NAME_STYLES)(twin.merchant_id),
                bank=self._cosmetic_rng.choice(_BANKS),
            )
            if self.rng.random() < 0.65:
                desc = self._attach_cycle(desc, twin.cycle_ref, held_out=held_out_cycle_phrasing)
                applied.append("cycle_ref_present")
            twin_bank = BankRow(
                bank_row_id=f"bnk_tw_{self.rng.randrange(16**8):08x}",
                description=desc,
                credit_amount=twin.amount,
                value_date=twin.value_date,
            )
            bank_rows.append(twin_bank)
            truth[twin.settlement_id] = twin_bank.bank_row_id
            corruptions[twin.settlement_id] = applied
            corruptions[original.settlement_id].append("identical_twin")

        self.rng.shuffle(settlements)
        self.rng.shuffle(bank_rows)
        return ThreeSourceBatch(
            settlements=settlements,
            bank_rows=bank_rows,
            ledger_rows=ledger_rows,
            truth=truth,
            corruptions=corruptions,
        )


def generate_three_source_batch(
    seed: int = 42,
    n: int = 120,
    collision_rate: float = 0.25,
    identical_twin_rate: float = 0.25,
    held_out_cycle_phrasing: bool = False,
) -> ThreeSourceBatch:
    return ThreeSourceGenerator(seed=seed).generate(
        n=n,
        collision_rate=collision_rate,
        identical_twin_rate=identical_twin_rate,
        held_out_cycle_phrasing=held_out_cycle_phrasing,
    )
